### ISSUE TITLE
building for windows?

### ISSUE THREAD

**Issue by delray** [drmpeg/gr-paint#22]
Hi,
Ive used gr-paint in the past with great success on ubuntu, but im giving 'radioconda' a try out and wondering if you had any tips on how to go about buidling grpaint to work with it. Maybe its impossible, but in case it matters GNU radio is v 3.10.8
thanks!

**Comment by drmpeg** [comment]
I'm afraid I know nothing about Windows. I haven't used it since XP. I'm going to tag @ryanvolz here and hopefully he'll respond.

**Comment by ryanvolz** [comment]
It's already built and included in radioconda, so nothing to do! I even re-built it about a week ago and included the latest commits! Look for it in GRC.

But to answer the question, you pretty much build as normal but with some extra CMake flags to point to the conda environment instead of the base system. The details are here: https://wiki.gnuradio.org/index.php/CondaInstall#Building_OOT_modules_to_use_with_conda-installed_GNU_Radio. Some OOT modules can be a pain on Windows if they do things that are not cross-platform, but that wasn't the case here.

**Comment by delray** [comment]
Well would you look at that - i should have paid a bit more attention :) I'm just coming back to all of this after a hiatus...thanks so much!
